#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="navalFoamVariant2"

runApplication blockMesh
cp 0/alpha1.org 0/alpha1
runApplication setFields
runApplication $application
