#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="navalFoam"

runApplication blockMesh
cp boundary constant/polyMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap
cp 0/alpha1.org 0/alpha1
runApplication setFields
runApplication $application
