#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="navalFoam"

# Mesh provided with the case
cp 0/alpha1.org 0/alpha1
runApplication setFields
runApplication $application
